In [1]:
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np


In [2]:
dataset = pd.read_csv("/content/Student Mental health1.csv")
dataset.head(13)

Timestamp Choose your gender  Age What is your course?  \
0   8/7/2020 12:02             Female   18          Engineering   
1   8/7/2020 12:04               Male   21    Islamic education   
2   8/7/2020 12:05               Male   19                  BIT   
3   8/7/2020 12:06             Female   22                 Laws   
4   8/7/2020 12:13               Male   23         Mathemathics   
5   8/7/2020 12:31               Male   19          Engineering   
6   8/7/2020 12:32             Female   23     Pendidikan islam   
7   8/7/2020 12:33             Female   18                  BCS   
8   8/7/2020 12:35             Female   19      Human Resources   
9   8/7/2020 12:39               Male   18                Irkhs   
10  8/7/2020 12:39             Female   20           Psychology   
11  8/7/2020 12:39             Female   24          Engineering   
12  8/7/2020 12:40             Female   18                  BCS   

   Your current year of Study What is your CGPA? Marital status  \
0                      year 1        3.00 - 3.49             No   
1                      year 2        3.00 - 3.49             No   
2                      Year 1        3.00 - 3.49             No   
3                      year 3        3.00 - 3.49            Yes   
4                      year 4        3.00 - 3.49             No   
5                      Year 2        3.50 - 4.00             No   
6                      year 2       3.50 - 4.00             Yes   
7                      year 1        3.50 - 4.00             No   
8                      Year 2        2.50 - 2.99             No   
9                      year 1        3.50 - 4.00             No   
10                     year 1        3.50 - 4.00             No   
11                     Year 3        3.50 - 4.00            Yes   
12                     year 1        3.00 - 3.49             No   

   Do you have Depression? Do you have Anxiety? Do you have Panic attack?  \
0                      Yes                   No                       Yes   
1                       No                  Yes                        No   
2                      Yes                  Yes                       Yes   
3                      Yes                   No                        No   
4                       No                   No                        No   
5                       No                   No                       Yes   
6                      Yes                   No                       Yes   
7                       No                  Yes                        No   
8                       No                   No                        No   
9                       No                  Yes                       Yes   
10                      No                   No                        No   
11                     Yes                   No                        No   
12                     Yes                   No                        No   

   Did you seek any specialist for a treatment?  
0                                            No  
1                                            No  
2                                            No  
3                                            No  
4                                            No  
5                                            No  
6                                            No  
7                                            No  
8                                            No  
9                                            No  
10                                           No  
11                                           No  
12                                           No

In [3]:
dataset_table1=pd.crosstab(dataset['Do you have Depression?'],dataset['Do you have Panic attack?'])
print(dataset_table1)

Do you have Panic attack?  No  Yes
Do you have Depression?           
No                         50   16
Yes                        18   17


In [4]:
dataset_table2=pd.crosstab(dataset['Choose your gender'],dataset['Marital status'])
print(dataset_table2)

Marital status      No  Yes
Choose your gender         
Female              62   13
Male                23    3


In [5]:
dataset_table3=pd.crosstab(dataset['Do you have Panic attack?'],dataset['Did you seek any specialist for a treatment?'])
print(dataset_table3)

Did you seek any specialist for a treatment?  No  Yes
Do you have Panic attack?                            
No                                            66    2
Yes                                           29    4


In [6]:
dataset_table1.values

array([[50, 16],
       [18, 17]])

In [7]:
dataset_table2.values

array([[62, 13],
       [23,  3]])

In [8]:
dataset_table3.values

array([[66,  2],
       [29,  4]])

In [9]:
#Observed Values 1
Observed_Values1 = dataset_table1.values 
print("Observed Values :-\n",Observed_Values1)

Observed Values :-
 [[50 16]
 [18 17]]


In [10]:
val=stats.chi2_contingency(dataset_table1)
val

(5.097741596638656, 0.02395701578316814, 1, array([[44.43564356, 21.56435644],
        [23.56435644, 11.43564356]]))

In [11]:
Expected_Values=val[3]

In [12]:
no_of_rows=len(dataset_table1.iloc[0:2,0])
no_of_columns=len(dataset_table1.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [13]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values1,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
     

In [14]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 6.154023813382103


In [15]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [16]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.01311134618521681
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.01311134618521681


In [17]:
#if chi_square_statistic>=critical_value:
 #   print("Reject H0,There is a relationship between 2 categorical variables")
#else:
 #   print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Reject H0,There is a relationship between 2 categorical variables


In [18]:
dataset_table2=pd.crosstab(dataset['Age'],dataset['Marital status'])
print(dataset_table2)

Marital status  No  Yes
Age                    
18              29    3
19              18    4
20               5    1
21               3    0
22               1    1
23              11    2
24              18    5


In [19]:
#Observed Values 3
Observed_Values = dataset_table3.values 
print("Observed Values :-\n",Observed_Values)
val=stats.chi2_contingency(dataset_table3)
val

Observed Values :-
 [[66  2]
 [29  4]]


(1.9093451934202705, 0.167036013771264, 1, array([[63.96039604,  4.03960396],
        [31.03960396,  1.96039604]]))

In [20]:
Expected_Values=val[3]

In [21]:
no_of_rows=len(dataset_table3.iloc[0:2,0])
no_of_columns=len(dataset_table3.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

Degree of Freedom:- 1


In [22]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [23]:
print("chi-square statistic:-",chi_square_statistic)
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

chi-square statistic:- 3.3508740657347467
critical_value: 3.841458820694124


In [24]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.0671693383085541
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.0671693383085541


In [25]:
   
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Retain H0,There is no relationship between 2 categorical variables


In [26]:
#Observed Values 2
Observed_Values = dataset_table2.values 
print("Observed Values :-\n",Observed_Values)
val=stats.chi2_contingency(dataset_table2)
val
Expected_Values=val[3]
no_of_rows=len(dataset_table2.iloc[0:2,0])
no_of_columns=len(dataset_table2.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:-",chi_square_statistic)
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

Observed Values :-
 [[29  3]
 [18  4]
 [ 5  1]
 [ 3  0]
 [ 1  1]
 [11  2]
 [18  5]]
Degree of Freedom:- 1
chi-square statistic:- 4.0142792033866606
critical_value: 3.841458820694124


In [27]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.04511650447069826
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.04511650447069826


In [28]:
   
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Reject H0,There is a relationship between 2 categorical variables
