In [ ]:
pip install -U scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 60.8 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2


In [ ]:
#importing module
from sklearn.decomposition import PCA 
import numpy as np 

In [ ]:
#dataset input
X = np.array([[1, 2, 3, 4], [5, 2, 1, 9], [3, 5, 7, 1], [5, 7, 4, 6], [2, 1, 6, 2]]) 
print(X)
print(X.shape) 
n_samples = X.shape[0]

[[1 2 3 4]
 [5 2 1 9]
 [3 5 7 1]
 [5 7 4 6]
 [2 1 6 2]]
(5, 4)


In [ ]:
pca = PCA(n_components=4,svd_solver='full') 
pca_score = pca.fit_transform(X) 
print('pca_score',pca_score,'\n') 
print('components',pca.components_,'\n') 
print('explained_variance',pca.explained_variance_ratio_,'\n') 
print('singular values',pca.singular_values_,'\n') 

pca_score [[-0.28797085 -2.41196245  1.58094575  0.01097643]
 [ 5.8892127  -1.17699635 -0.72358467  0.09098672]
 [-4.26609677  1.92649882 -0.24274891  0.17347524]
 [ 1.87419578  3.89316327  0.33608887 -0.1330949 ]
 [-3.20934086 -2.23070328 -0.95070103 -0.14234349]] 

components [[ 0.28919934 -0.00326412 -0.5480359   0.78486288]
 [ 0.40219495  0.88498026  0.23387227  0.01878617]
 [-0.72857175  0.46427116 -0.49768238 -0.07712163]
 [ 0.47306042 -0.03537764 -0.6302957  -0.61456456]] 

explained_variance [0.65468445 0.30438273 0.04018313 0.00074969] 

singular values [8.17176931 5.57198693 2.02451956 0.27652964] 



In [ ]:
#center the data and compute the sample covariance matrix 
X_centered = X - np.mean(X, axis=0) 
cov_matrix = np.dot(X_centered.T, X_centered) / n_samples 
eigenvalues = pca.explained_variance_
print('eigenvalues ',eigenvalues) 

pca = PCA(n_components=2) 

principalComponents = pca.fit_transform(X) 

print('\t    ',pca.explained_variance_ratio_) 
print('\t    ',pca.singular_values_)

eigenvalues  [16.69445341  7.76175957]
	     [0.65468445 0.30438273]
	     [8.17176931 5.57198693]
